<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>User Login Scenarios</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>29d53c1f-d9ba-4e7c-9f58-0fd03b31707b</testSuiteGuid>
   <testCaseLink>
      <guid>65ed5a9a-86d2-4744-ab5d-a7308f9bb4d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Validate - Missing Password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4faa1902-722d-46a3-8bbd-f488fb0e8ff0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ae0ffb7-d7b1-49aa-b15d-a88bb081f200</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5cbf66f4-ffc7-41f7-8c5e-25418c00b975</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Validate - Missing Username</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64214f96-968c-48e4-bbd8-495e1c8399c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac839ebc-1816-4179-b201-8813b96f89c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e2e355d-5224-45e1-873b-2823b355418a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Validate -Invalid Credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1803ef88-4355-409d-b0ef-a93ab0bdd31e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4ca954e-4e1b-4dc4-b77d-9b976a7a03ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b06b90d4-eb7d-429c-8b99-701c6a5a21af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Verify - Succesful Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bde18f4-12be-414c-9e71-ee94a00bd5f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65221487-5579-4f09-9ed2-77dc315a6b70</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
