<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//button[@type='submit'][contains(.,'Login')]</description>
   <name>Button_Login</name>
   <tag></tag>
   <elementGuidId>b0a206ee-e167-4065-9bf8-135faf225f9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit'][contains(.,'Login')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
